import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function test() {
  return (
    <>
    <Head>
        <title>Testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Testing Speed &nbsp;
            <code className={styles.code}>Server</code>
          </p>
      
        </div>
       
        <div className={styles.bl}>
         
          <h3 className={styles.tex}>
            Server Speed
          </h3>
          <div className={styles.thirteen}>
            <Image
              src="/server.png"
              alt="server"
              width={39}
              height={31}
              priority
            />
          </div>
        </div>
        <div className={styles.speed}>
            <h3>Video & Photo Speed Testing</h3><br></br>
            <div className={styles.grid}>
                 <a 
            className={styles.card}
            href='/stock.mp4'>
                <h2 className={inter.className}>1080P Full Hd</h2>

            </a>          
            <a href='/4k.mp4' 
            className={styles.card}
            >
                <h2 className={inter.className}>$ 4K</h2>
            </a>
            <a className={styles.card} href='/32k.png'><h2 className={inter.className}>$32 K photo</h2> <p>Note photo rendering ms 24ms</p></a>
            </div>
            <div className={styles.card}>
              <h1 className={styles.tex}>Advance Speed Test</h1>
              
            </div>
           

        </div>

        
      </main>
    </>
  )
}